#include "TextureRects.hpp"

sf::IntRect TextureRects::room_house_aon_livingroom = sf::IntRect(0, 0, 305, 163);
sf::IntRect TextureRects::character_neamly_overworld_finalform1 = sf::IntRect(305, 0, 177, 163);
sf::IntRect TextureRects::room_beach_1 = sf::IntRect(482, 0, 195, 162);
sf::IntRect TextureRects::room_beach_0 = sf::IntRect(677, 0, 195, 162);
sf::IntRect TextureRects::room_house_aon_hallway = sf::IntRect(872, 0, 286, 147);
sf::IntRect TextureRects::room_house_aon_downstairs = sf::IntRect(1158, 0, 225, 147);
sf::IntRect TextureRects::object_house_aon_0 = sf::IntRect(872, 147, 206, 134);
sf::IntRect TextureRects::room_house_aon_kitchen = sf::IntRect(1078, 147, 101, 132);
sf::IntRect TextureRects::object_palmTree = sf::IntRect(1179, 147, 87, 123);
sf::IntRect TextureRects::character_fauster_fight_idle_0 = sf::IntRect(1266, 147, 68, 118);
sf::IntRect TextureRects::object_llamaBay_store = sf::IntRect(1266, 265, 107, 117);
sf::IntRect TextureRects::character_flirtingDoggoLogo = sf::IntRect(1179, 270, 73, 111);
sf::IntRect TextureRects::character_martoonitgamer_fight_idle_0 = sf::IntRect(1334, 147, 36, 106);
sf::IntRect TextureRects::room_house_aon_guestroom = sf::IntRect(482, 162, 113, 104);
sf::IntRect TextureRects::character_blackatackle_fight_idle_0 = sf::IntRect(1078, 279, 92, 102);
sf::IntRect TextureRects::character_blueman_overworld_down_talking = sf::IntRect(595, 162, 60, 100);
sf::IntRect TextureRects::character_blueman_overworld_down = sf::IntRect(655, 162, 60, 100);
sf::IntRect TextureRects::object_house_aon_livingroom_wall = sf::IntRect(715, 162, 36, 99);
sf::IntRect TextureRects::object_house_shop_keeper = sf::IntRect(751, 162, 83, 98);
sf::IntRect TextureRects::character_weirdSquidDog_fight_idle_0 = sf::IntRect(751, 260, 61, 97);
sf::IntRect TextureRects::room_intro_2 = sf::IntRect(595, 262, 115, 96);
sf::IntRect TextureRects::room_intro_4 = sf::IntRect(812, 281, 115, 96);
sf::IntRect TextureRects::room_intro_1 = sf::IntRect(927, 281, 115, 96);
sf::IntRect TextureRects::room_intro_0 = sf::IntRect(0, 163, 115, 96);
sf::IntRect TextureRects::room_intro_3 = sf::IntRect(115, 163, 115, 95);
sf::IntRect TextureRects::character_pinkRabbit_fight_idle_0 = sf::IntRect(710, 357, 56, 93);
sf::IntRect TextureRects::object_shopinthewoods = sf::IntRect(230, 163, 92, 91);
sf::IntRect TextureRects::object_house_aon_1 = sf::IntRect(230, 254, 206, 90);
sf::IntRect TextureRects::object_house_lab = sf::IntRect(115, 258, 83, 89);
sf::IntRect TextureRects::object_house_aon_hallway_wall = sf::IntRect(1370, 147, 24, 86);
sf::IntRect TextureRects::character_neamly_overworld_spooky_down = sf::IntRect(834, 162, 37, 81);
sf::IntRect TextureRects::character_neamly_overworld_down = sf::IntRect(710, 262, 37, 81);
sf::IntRect TextureRects::character_lissey_fight_idle_0 = sf::IntRect(766, 357, 39, 80);
sf::IntRect TextureRects::character_hauntedRobot_overworld_down_evil = sf::IntRect(198, 258, 31, 80);
sf::IntRect TextureRects::character_reiny_fight_idle_0 = sf::IntRect(0, 259, 53, 78);
sf::IntRect TextureRects::character_blueman_closeup_neutral = sf::IntRect(0, 337, 63, 75);
sf::IntRect TextureRects::object_house_0 = sf::IntRect(53, 259, 60, 70);
sf::IntRect TextureRects::object_llamaBay_rocks = sf::IntRect(805, 377, 195, 67);
sf::IntRect TextureRects::character_llamateen_fight_idle_itch_0 = sf::IntRect(198, 338, 25, 67);
sf::IntRect TextureRects::character_llamateen_fight_idle_itch_1 = sf::IntRect(1042, 281, 25, 67);
sf::IntRect TextureRects::character_llamateen_fight_idle_1 = sf::IntRect(1373, 233, 22, 67);
sf::IntRect TextureRects::character_llamateen_fight_idle_0 = sf::IntRect(1373, 300, 22, 67);
sf::IntRect TextureRects::character_caroline_fight_idle_0 = sf::IntRect(1000, 377, 55, 66);
sf::IntRect TextureRects::UI_floatingMenu = sf::IntRect(63, 347, 62, 65);
sf::IntRect TextureRects::character_weirdo_overworld_left_walking_0 = sf::IntRect(125, 347, 58, 62);
sf::IntRect TextureRects::character_weirdo_overworld_left_walking_1 = sf::IntRect(436, 266, 58, 62);
sf::IntRect TextureRects::character_art_fight_dead = sf::IntRect(494, 266, 83, 61);
sf::IntRect TextureRects::character_art_fight_idle_0 = sf::IntRect(494, 327, 83, 61);
sf::IntRect TextureRects::character_art_fight_idle_1 = sf::IntRect(577, 358, 83, 61);
sf::IntRect TextureRects::character_art_fight_hurt = sf::IntRect(322, 163, 83, 61);
sf::IntRect TextureRects::character_weirdo_overworld_left_talking = sf::IntRect(436, 328, 58, 61);
sf::IntRect TextureRects::character_weirdo_overworld_left = sf::IntRect(405, 163, 58, 61);
sf::IntRect TextureRects::character_dogplane_fight_idle_0 = sf::IntRect(1055, 381, 113, 60);
sf::IntRect TextureRects::object_battleEffect_hit_1 = sf::IntRect(494, 388, 80, 60);
sf::IntRect TextureRects::object_battleEffect_hit_3 = sf::IntRect(1168, 381, 80, 60);
sf::IntRect TextureRects::object_battleEffect_hit_2 = sf::IntRect(574, 419, 80, 60);
sf::IntRect TextureRects::object_battleEffect_hit_0 = sf::IntRect(1248, 382, 80, 60);
sf::IntRect TextureRects::object_house_diner = sf::IntRect(1055, 441, 98, 58);
sf::IntRect TextureRects::character_snorrplurp_fight_idle_2 = sf::IntRect(223, 344, 102, 57);
sf::IntRect TextureRects::character_snorplorp_fight_idle_0 = sf::IntRect(325, 344, 102, 57);
sf::IntRect TextureRects::character_snorrplurp_fight_idle_1 = sf::IntRect(1153, 442, 102, 57);
sf::IntRect TextureRects::character_ducko_fight_idle_0 = sf::IntRect(766, 437, 33, 57);
sf::IntRect TextureRects::character_ducko_fight_howDareYou_0 = sf::IntRect(660, 358, 33, 57);
sf::IntRect TextureRects::character_ducko_fight_howDareYou_1 = sf::IntRect(660, 415, 33, 57);
sf::IntRect TextureRects::character_ducko_fight_howDareYou_2 = sf::IntRect(1000, 443, 33, 57);
sf::IntRect TextureRects::object_house_aon_guestroom_bed = sf::IntRect(1328, 382, 29, 52);
sf::IntRect TextureRects::character_nuayde_fight_idle_body = sf::IntRect(654, 472, 93, 51);
sf::IntRect TextureRects::character_bunny_overworld_down = sf::IntRect(1357, 382, 25, 49);
sf::IntRect TextureRects::object_house_random_0 = sf::IntRect(1255, 442, 74, 47);
sf::IntRect TextureRects::room_gameOver = sf::IntRect(1329, 434, 53, 47);
sf::IntRect TextureRects::character_personAndCamel_overworld_left = sf::IntRect(1329, 481, 39, 47);
sf::IntRect TextureRects::character_personAndCamel_overworld_left_2 = sf::IntRect(427, 389, 39, 47);
sf::IntRect TextureRects::character_camel_overworld_idle_0 = sf::IntRect(1255, 489, 39, 47);
sf::IntRect TextureRects::character_personAndCamel_overworld_down_1 = sf::IntRect(799, 444, 39, 47);
sf::IntRect TextureRects::character_camel_overworld_idle_1 = sf::IntRect(838, 444, 39, 47);
sf::IntRect TextureRects::object_house_aon_livingroom_granpaClock_1 = sf::IntRect(463, 163, 19, 47);
sf::IntRect TextureRects::object_house_aon_livingroom_granpaClock_0 = sf::IntRect(747, 450, 19, 47);
sf::IntRect TextureRects::object_house_aon_livingroom_granpaClock_2 = sf::IntRect(463, 210, 19, 47);
sf::IntRect TextureRects::character_limespider_fight_idle_booty = sf::IntRect(949, 444, 49, 46);
sf::IntRect TextureRects::character_llamaBaby_fight_hit = sf::IntRect(949, 490, 36, 46);
sf::IntRect TextureRects::character_llamaBaby_fight_idle_0 = sf::IntRect(799, 491, 36, 46);
sf::IntRect TextureRects::character_llamaBaby_fight_idle_1 = sf::IntRect(747, 497, 36, 46);
sf::IntRect TextureRects::UI_textbox = sf::IntRect(223, 401, 160, 45);
sf::IntRect TextureRects::character_dadAvocado_overworld_down_talking_0 = sf::IntRect(183, 405, 37, 44);
sf::IntRect TextureRects::character_dadAvocado_overworld_down_talking_1 = sf::IntRect(383, 401, 37, 44);
sf::IntRect TextureRects::character_avocadomayor_overworld_down = sf::IntRect(125, 409, 40, 43);
sf::IntRect TextureRects::character_sundeh_overworld_right = sf::IntRect(420, 436, 49, 40);
sf::IntRect TextureRects::character_sundeh_overworld_left = sf::IntRect(469, 448, 49, 40);
sf::IntRect TextureRects::character_creepyGhost_closeup_glitch_1 = sf::IntRect(518, 448, 54, 39);
sf::IntRect TextureRects::character_creepyGhost_closeup_glitch_0 = sf::IntRect(572, 479, 54, 39);
sf::IntRect TextureRects::character_creepyGhost_closeup_glitch_2 = sf::IntRect(518, 487, 54, 39);
sf::IntRect TextureRects::character_creepyGhost_closeup_neutral = sf::IntRect(572, 518, 44, 39);
sf::IntRect TextureRects::character_creepyGhost_closeup_red = sf::IntRect(835, 491, 44, 39);
sf::IntRect TextureRects::character_sundeh_overworld_down = sf::IntRect(466, 389, 28, 39);
sf::IntRect TextureRects::character_sundeh_overworld_up = sf::IntRect(626, 479, 28, 39);
sf::IntRect TextureRects::character_oldAvocadoAndDog_overworld_left_1 = sf::IntRect(879, 491, 49, 36);
sf::IntRect TextureRects::character_confusnake_fight_idle_0 = sf::IntRect(1294, 489, 33, 36);
sf::IntRect TextureRects::character_handman_overworld_down_1 = sf::IntRect(1368, 481, 26, 36);
sf::IntRect TextureRects::character_handman_overworld_down = sf::IntRect(436, 224, 26, 36);
sf::IntRect TextureRects::character_aon_overworld_newspaper_1 = sf::IntRect(1033, 443, 22, 36);
sf::IntRect TextureRects::character_aon_overworld_newspaper_1_talking = sf::IntRect(1033, 479, 22, 36);
sf::IntRect TextureRects::object_house_aon_tv = sf::IntRect(1368, 517, 22, 36);
sf::IntRect TextureRects::character_oldAvocadoAndDog_overworld_left = sf::IntRect(0, 412, 49, 35);
sf::IntRect TextureRects::character_oldAvocadoAndDog_overworld_left_2 = sf::IntRect(49, 412, 49, 35);
sf::IntRect TextureRects::character_buggy_fight_idle_0 = sf::IntRect(383, 445, 32, 35);
sf::IntRect TextureRects::character_buggy_fight_idle_1 = sf::IntRect(834, 243, 32, 35);
sf::IntRect TextureRects::character_aon_closeup_heh = sf::IntRect(928, 491, 21, 35);
sf::IntRect TextureRects::character_aon_closeup_happy_talking = sf::IntRect(98, 412, 21, 35);
sf::IntRect TextureRects::character_aon_closeup_happy = sf::IntRect(616, 518, 21, 35);
sf::IntRect TextureRects::character_aon_closeup_suprised = sf::IntRect(985, 500, 21, 35);
sf::IntRect TextureRects::character_aon_closeup_sad_talking = sf::IntRect(1006, 500, 21, 35);
sf::IntRect TextureRects::character_aon_closeup_suprised_talking = sf::IntRect(415, 476, 21, 35);
sf::IntRect TextureRects::character_aon_closeup_sweat = sf::IntRect(436, 476, 21, 35);
sf::IntRect TextureRects::character_aon_closeup_sweat_talking = sf::IntRect(457, 488, 21, 35);
sf::IntRect TextureRects::character_aon_closeup_angry = sf::IntRect(478, 488, 21, 35);
sf::IntRect TextureRects::character_aon_closeup_angry_talking = sf::IntRect(637, 523, 21, 35);
sf::IntRect TextureRects::character_aon_closeup_sad = sf::IntRect(658, 523, 21, 35);
sf::IntRect TextureRects::character_aon_closeup_huh_talking = sf::IntRect(679, 523, 21, 35);
sf::IntRect TextureRects::character_aon_closeup_huh = sf::IntRect(700, 523, 21, 35);
sf::IntRect TextureRects::character_aon_closeup_heh_talking = sf::IntRect(721, 523, 21, 35);
sf::IntRect TextureRects::character_aon_overworld_down_walking_1 = sf::IntRect(183, 347, 15, 35);
sf::IntRect TextureRects::character_aon_overworld_up_walking_1 = sf::IntRect(783, 494, 15, 35);
sf::IntRect TextureRects::character_aon_overworld_up_walking_0 = sf::IntRect(693, 358, 15, 35);
sf::IntRect TextureRects::character_aon_overworld_down = sf::IntRect(693, 393, 15, 35);
sf::IntRect TextureRects::character_aon_overworld_down_talking = sf::IntRect(693, 428, 15, 35);
sf::IntRect TextureRects::character_aon_overworld_down_walking_0 = sf::IntRect(577, 266, 15, 35);
sf::IntRect TextureRects::character_aon_overworld_up = sf::IntRect(165, 409, 15, 35);
sf::IntRect TextureRects::character_aon_overworld_right_walking_0 = sf::IntRect(1382, 367, 13, 35);
sf::IntRect TextureRects::character_aon_overworld_right_walking_1 = sf::IntRect(1382, 402, 13, 35);
sf::IntRect TextureRects::character_aon_overworld_left_walking_1 = sf::IntRect(1382, 437, 13, 35);
sf::IntRect TextureRects::character_aon_overworld_left = sf::IntRect(1252, 270, 13, 35);
sf::IntRect TextureRects::character_aon_overworld_left_walking_0 = sf::IntRect(1252, 305, 13, 35);
sf::IntRect TextureRects::character_aon_overworld_left_walking_0_worried = sf::IntRect(1252, 340, 13, 35);
sf::IntRect TextureRects::character_aon_overworld_left_walking_1_worried = sf::IntRect(577, 301, 13, 35);
sf::IntRect TextureRects::character_aon_overworld_left_worried = sf::IntRect(165, 444, 13, 35);
sf::IntRect TextureRects::character_aon_overworld_onLegs_left_0 = sf::IntRect(499, 488, 13, 35);
sf::IntRect TextureRects::character_aon_overworld_right = sf::IntRect(0, 447, 13, 35);
sf::IntRect TextureRects::character_flynn_tired = sf::IntRect(13, 447, 42, 34);
sf::IntRect TextureRects::object_house_diner_door_2 = sf::IntRect(55, 447, 19, 34);
sf::IntRect TextureRects::object_house_diner_door_1 = sf::IntRect(74, 447, 19, 34);
sf::IntRect TextureRects::object_house_diner_door_3 = sf::IntRect(93, 447, 19, 34);
sf::IntRect TextureRects::object_house_diner_door_0 = sf::IntRect(112, 452, 19, 34);
sf::IntRect TextureRects::character_nuayde_fight_idle_arm_left_0 = sf::IntRect(131, 452, 16, 34);
sf::IntRect TextureRects::character_nuayde_fight_idle_arm_left_1 = sf::IntRect(147, 452, 16, 34);
sf::IntRect TextureRects::character_nuayde_fight_idle_arm_right_0 = sf::IntRect(13, 481, 16, 34);
sf::IntRect TextureRects::character_nuayde_fight_idle_arm_right_1 = sf::IntRect(29, 481, 16, 34);
sf::IntRect TextureRects::character_avocadoGuy_overworld_down = sf::IntRect(1294, 525, 30, 33);
sf::IntRect TextureRects::character_avocadoGuy_overworld_down_talking = sf::IntRect(45, 481, 30, 33);
sf::IntRect TextureRects::character_aon_overworld_onLegs_left_talking = sf::IntRect(1055, 348, 15, 33);
sf::IntRect TextureRects::character_aon_overworld_onLegs_left = sf::IntRect(75, 481, 15, 33);
sf::IntRect TextureRects::character_aon_overworld_onLegs_left_1 = sf::IntRect(90, 481, 15, 33);
sf::IntRect TextureRects::object_house_aon_guestroom_bed_overlay = sf::IntRect(220, 446, 31, 32);
sf::IntRect TextureRects::character_aon_overworld_newspaper_0 = sf::IntRect(178, 449, 22, 32);
sf::IntRect TextureRects::character_flynn_overworld_snoring_0 = sf::IntRect(200, 449, 17, 32);
sf::IntRect TextureRects::character_flynn_overworld_up_walking_1 = sf::IntRect(928, 526, 17, 32);
sf::IntRect TextureRects::character_flynn_overworld_up_walking_0 = sf::IntRect(251, 446, 17, 32);
sf::IntRect TextureRects::character_flynn_overworld_snoring_1 = sf::IntRect(268, 446, 17, 32);
sf::IntRect TextureRects::character_flynn_overworld_right = sf::IntRect(285, 446, 17, 32);
sf::IntRect TextureRects::character_flynn_overworld_left_walking_1 = sf::IntRect(302, 446, 17, 32);
sf::IntRect TextureRects::character_flynn_overworld_left_walking_0 = sf::IntRect(319, 446, 17, 32);
sf::IntRect TextureRects::character_flynn_overworld_left_sitting = sf::IntRect(336, 446, 17, 32);
sf::IntRect TextureRects::character_flynn_overworld_left = sf::IntRect(353, 446, 17, 32);
sf::IntRect TextureRects::character_flynn_overworld_down_walking_1 = sf::IntRect(217, 478, 17, 32);
sf::IntRect TextureRects::character_flynn_overworld_down_walking_0 = sf::IntRect(163, 481, 17, 32);
sf::IntRect TextureRects::character_flynn_overworld_down = sf::IntRect(180, 481, 17, 32);
sf::IntRect TextureRects::character_flynn_overworld_up = sf::IntRect(197, 481, 17, 32);
sf::IntRect TextureRects::UI_title = sf::IntRect(234, 478, 106, 31);
sf::IntRect TextureRects::character_flynn_overworld_right_walking_0 = sf::IntRect(340, 478, 17, 31);
sf::IntRect TextureRects::character_flynn_overworld_right_walking_1 = sf::IntRect(357, 478, 17, 31);
sf::IntRect TextureRects::character_nuayde_fight_idle_face_hurt = sf::IntRect(374, 480, 21, 30);
sf::IntRect TextureRects::character_nuayde_fight_idle_face = sf::IntRect(1324, 528, 21, 30);
sf::IntRect TextureRects::character_nuayde_fight_idle_face_rip = sf::IntRect(1345, 528, 21, 30);
sf::IntRect TextureRects::character_pinkshirtedllama_overworld_down_walking_0 = sf::IntRect(0, 482, 13, 30);
sf::IntRect TextureRects::character_pinkshirtedllama_overworld_down_walking_1 = sf::IntRect(370, 446, 13, 30);
sf::IntRect TextureRects::character_pinkshirtedllama_overworld_down = sf::IntRect(0, 512, 13, 30);
sf::IntRect TextureRects::character_pinkshirtedllama_overworld_down_talking = sf::IntRect(1042, 348, 13, 29);
sf::IntRect TextureRects::object_house_aon_livingroom_table = sf::IntRect(322, 224, 113, 28);
sf::IntRect TextureRects::object_pomHeadStatue = sf::IntRect(879, 527, 24, 28);
sf::IntRect TextureRects::character_pinkRabbit_overworld_down_talking = sf::IntRect(783, 529, 14, 28);
sf::IntRect TextureRects::character_pinkRabbit_overworld_down = sf::IntRect(395, 480, 14, 28);
sf::IntRect TextureRects::character_pinkRabbit_overworld_down_walking_0 = sf::IntRect(395, 508, 14, 28);
sf::IntRect TextureRects::object_house_aon_livingroom_couch = sf::IntRect(409, 511, 47, 26);
sf::IntRect TextureRects::character_avocadoBoy_overworld_down_talking_1 = sf::IntRect(903, 527, 21, 26);
sf::IntRect TextureRects::object_fire_0 = sf::IntRect(835, 530, 16, 26);
sf::IntRect TextureRects::object_fire_2 = sf::IntRect(851, 530, 15, 26);
sf::IntRect TextureRects::object_house_aon_gramophone = sf::IntRect(105, 486, 15, 26);
sf::IntRect TextureRects::object_fire_1 = sf::IntRect(120, 486, 15, 26);
sf::IntRect TextureRects::character_margret_lemonadeStand = sf::IntRect(135, 486, 14, 26);
sf::IntRect TextureRects::character_magret_lemonadeStand_talking = sf::IntRect(149, 486, 14, 26);
sf::IntRect TextureRects::object_pomStatue = sf::IntRect(105, 512, 27, 25);
sf::IntRect TextureRects::character_avocadoBoy_overworld_down_talking_0 = sf::IntRect(132, 512, 21, 25);
sf::IntRect TextureRects::character_avocadoBoy_overworld_down = sf::IntRect(45, 514, 15, 25);
sf::IntRect TextureRects::character_tailance_overworld_down = sf::IntRect(866, 530, 13, 25);
sf::IntRect TextureRects::character_lissey_overworld_down = sf::IntRect(13, 515, 13, 25);
sf::IntRect TextureRects::character_joggingsnake_overworld_left = sf::IntRect(60, 514, 34, 24);
sf::IntRect TextureRects::character_joggingsnake_overworld_left_walking_0 = sf::IntRect(456, 523, 34, 24);
sf::IntRect TextureRects::character_joggingsnake_overworld_left_walking_1 = sf::IntRect(490, 526, 34, 24);
sf::IntRect TextureRects::character_cat_fight_idle_0 = sf::IntRect(524, 526, 31, 24);
sf::IntRect TextureRects::character_cat_fight_idle_1 = sf::IntRect(234, 509, 31, 24);
sf::IntRect TextureRects::character_birdhat_overworld_left_talking = sf::IntRect(153, 513, 23, 24);
sf::IntRect TextureRects::character_birdhat_overworld_left = sf::IntRect(176, 513, 23, 24);
sf::IntRect TextureRects::character_creepyGhost_overworld_down_red_1 = sf::IntRect(555, 526, 17, 24);
sf::IntRect TextureRects::character_creepyghost_overworld_down_red_0 = sf::IntRect(26, 515, 17, 24);
sf::IntRect TextureRects::character_creepyGhost_overworld_down_appearing_8 = sf::IntRect(214, 510, 17, 24);
sf::IntRect TextureRects::character_creepyGhost_overworld_down_appearing_7 = sf::IntRect(265, 509, 17, 24);
sf::IntRect TextureRects::character_creepyGhost_overworld_down_appearing_6 = sf::IntRect(282, 509, 17, 24);
sf::IntRect TextureRects::character_creepyGhost_overworld_down_red_3 = sf::IntRect(299, 509, 17, 24);
sf::IntRect TextureRects::character_creepyGhost_overworld_down_appearing_5 = sf::IntRect(316, 509, 17, 24);
sf::IntRect TextureRects::character_creepyGhost_overworld_down_appearing_4 = sf::IntRect(333, 509, 17, 24);
sf::IntRect TextureRects::character_creepyGhost_overworld_down_talking_creepy_0 = sf::IntRect(350, 509, 17, 24);
sf::IntRect TextureRects::character_creepyGhost_overworld_down_appearing_3 = sf::IntRect(367, 510, 17, 24);
sf::IntRect TextureRects::character_creepyGhost_overworld_down_appearing_2 = sf::IntRect(231, 533, 17, 24);
sf::IntRect TextureRects::character_creepyGhost_overworld_down_talking_creepy_1 = sf::IntRect(199, 534, 17, 24);
sf::IntRect TextureRects::character_creepyGhost_overworld_down = sf::IntRect(248, 533, 17, 24);
sf::IntRect TextureRects::character_creepyGhost_overworld_down_red_2 = sf::IntRect(265, 533, 17, 24);
sf::IntRect TextureRects::character_creepyGhost_overworld_down_talking = sf::IntRect(282, 533, 17, 24);
sf::IntRect TextureRects::UI_hearts = sf::IntRect(299, 533, 62, 23);
sf::IntRect TextureRects::character_limespider_fight_idle_leg_right_2 = sf::IntRect(1055, 499, 40, 23);
sf::IntRect TextureRects::character_limespider_fight_idle_leg_left_2 = sf::IntRect(1095, 499, 40, 23);
sf::IntRect TextureRects::object_checkpoint_open = sf::IntRect(1027, 515, 21, 23);
sf::IntRect TextureRects::object_checkpoint_closed = sf::IntRect(361, 534, 21, 23);
sf::IntRect TextureRects::character_depressedAvocado_overworld_right = sf::IntRect(985, 535, 20, 23);
sf::IntRect TextureRects::character_depressedAvocado_overworld_right_walking_1 = sf::IntRect(1005, 535, 20, 23);
sf::IntRect TextureRects::character_creepyGhost_overworld_down_appearing_1 = sf::IntRect(183, 382, 15, 23);
sf::IntRect TextureRects::character_depressedAvocado_overworld_right_walking_0 = sf::IntRect(382, 536, 20, 22);
sf::IntRect TextureRects::character_limespider_fight_idle_leg_right_1 = sf::IntRect(402, 537, 44, 21);
sf::IntRect TextureRects::character_limespider_fight_idle_leg_left_1 = sf::IntRect(94, 537, 44, 21);
sf::IntRect TextureRects::object_whoopeeCushion = sf::IntRect(797, 537, 25, 21);
sf::IntRect TextureRects::character_cat_overworld_down = sf::IntRect(708, 450, 23, 21);
sf::IntRect TextureRects::character_cat_overworld_down_talking_1 = sf::IntRect(945, 536, 23, 21);
sf::IntRect TextureRects::character_limespider_fight_idle_face_2 = sf::IntRect(812, 260, 21, 21);
sf::IntRect TextureRects::character_limespider_fight_idle_face_4 = sf::IntRect(138, 537, 21, 21);
sf::IntRect TextureRects::character_limespider_fight_idle_face_5 = sf::IntRect(159, 537, 21, 21);
sf::IntRect TextureRects::character_limespider_fight_idle_face_3 = sf::IntRect(1135, 499, 21, 21);
sf::IntRect TextureRects::character_limespider_fight_idle_face_6 = sf::IntRect(1156, 499, 21, 21);
sf::IntRect TextureRects::character_limespider_fight_idle_face_7 = sf::IntRect(1177, 499, 21, 21);
sf::IntRect TextureRects::character_limespider_fight_idle_face_1 = sf::IntRect(1198, 499, 21, 21);
sf::IntRect TextureRects::character_limespider_fight_idle_face_0 = sf::IntRect(1219, 499, 21, 21);
sf::IntRect TextureRects::character_limespider_fight_idle_leg_right_0 = sf::IntRect(1135, 520, 39, 20);
sf::IntRect TextureRects::character_limespider_fight_idle_leg_left_0 = sf::IntRect(1174, 520, 39, 20);
sf::IntRect TextureRects::character_sandperson_0_overworld_down = sf::IntRect(469, 428, 22, 20);
sf::IntRect TextureRects::character_sandperson_0_overworld_down_talking = sf::IntRect(60, 538, 22, 20);
sf::IntRect TextureRects::object_lemonadeStand_table = sf::IntRect(1213, 520, 39, 19);
sf::IntRect TextureRects::character_limespider_fight_idle_leg_right_3 = sf::IntRect(26, 539, 26, 19);
sf::IntRect TextureRects::character_limespider_fight_idle_leg_left_3 = sf::IntRect(1252, 536, 26, 19);
sf::IntRect TextureRects::character_limespider_fight_idle_fangs_0 = sf::IntRect(968, 536, 17, 19);
sf::IntRect TextureRects::character_limespider_fight_idle_fangs_1 = sf::IntRect(577, 336, 17, 19);
sf::IntRect TextureRects::character_buggy_overworld_down = sf::IntRect(731, 450, 16, 19);
sf::IntRect TextureRects::character_buggy_overworld_downtalk = sf::IntRect(1278, 536, 16, 19);
sf::IntRect TextureRects::character_buggy_overworld_down_walking_0 = sf::IntRect(180, 537, 16, 19);
sf::IntRect TextureRects::character_buggy_overworld_up = sf::IntRect(1213, 539, 16, 19);
sf::IntRect TextureRects::character_buggy_overworld_down_walking_1 = sf::IntRect(1229, 539, 16, 19);
sf::IntRect TextureRects::object_house_aon_avocadoPlant = sf::IntRect(199, 513, 15, 19);
sf::IntRect TextureRects::object_table = sf::IntRect(216, 534, 15, 19);
sf::IntRect TextureRects::object_house_aon_plant = sf::IntRect(1383, 0, 12, 19);
sf::IntRect TextureRects::character_ducko_overworld_left_walking_0 = sf::IntRect(446, 537, 10, 19);
sf::IntRect TextureRects::character_ducko_overworld_left_walking_1 = sf::IntRect(1067, 281, 10, 19);
sf::IntRect TextureRects::character_ducko_overworld_left = sf::IntRect(384, 510, 10, 19);
sf::IntRect TextureRects::character_dogplane_overworld_right = sf::IntRect(63, 329, 47, 18);
sf::IntRect TextureRects::character_flynn_overworld_lying = sf::IntRect(1048, 522, 39, 18);
sf::IntRect TextureRects::object_minecart_side_1 = sf::IntRect(1087, 522, 33, 18);
sf::IntRect TextureRects::object_minecart_side_0 = sf::IntRect(1025, 540, 33, 18);
sf::IntRect TextureRects::object_minecart_down_0 = sf::IntRect(1058, 540, 23, 18);
sf::IntRect TextureRects::object_minecart_down_1 = sf::IntRect(1081, 540, 23, 18);
sf::IntRect TextureRects::character_creepyGhost_overworld_down_appearing_0 = sf::IntRect(94, 514, 11, 18);
sf::IntRect TextureRects::character_art_overworld_down_walking_1 = sf::IntRect(0, 542, 21, 16);
sf::IntRect TextureRects::character_cuteDog_overworld_down = sf::IntRect(1104, 540, 16, 16);
sf::IntRect TextureRects::UI_button_left = sf::IntRect(1120, 540, 16, 16);
sf::IntRect TextureRects::character_art_overworld_down = sf::IntRect(742, 543, 21, 15);
sf::IntRect TextureRects::character_art_overworld_down_walking_0 = sf::IntRect(1136, 540, 21, 15);
sf::IntRect TextureRects::UI_button_left_pressed = sf::IntRect(763, 543, 16, 15);
sf::IntRect TextureRects::object_rail_down = sf::IntRect(1067, 300, 11, 15);
sf::IntRect TextureRects::object_house_aon_lamp = sf::IntRect(1170, 279, 9, 13);
sf::IntRect TextureRects::UI_heart = sf::IntRect(822, 537, 13, 12);
sf::IntRect TextureRects::object_bone = sf::IntRect(457, 476, 12, 12);
sf::IntRect TextureRects::character_sandperson_1_overworld_down = sf::IntRect(985, 490, 13, 10);
sf::IntRect TextureRects::UI_button_johnCena_pressed = sf::IntRect(427, 344, 9, 9);
sf::IntRect TextureRects::UI_button_johnCena = sf::IntRect(1373, 367, 9, 9);
sf::IntRect TextureRects::object_dogFood = sf::IntRect(53, 329, 10, 8);
sf::IntRect TextureRects::object_cat = sf::IntRect(82, 538, 12, 7);
sf::IntRect TextureRects::object_rail_right = sf::IntRect(693, 463, 15, 3);

sf::IntRect TextureRects::getTextureRectFromName(const std::string& p_name) {
	if (p_name == "room_house_aon_livingroom") return TextureRects::room_house_aon_livingroom;
	if (p_name == "character_neamly_overworld_finalform1") return TextureRects::character_neamly_overworld_finalform1;
	if (p_name == "room_beach_1") return TextureRects::room_beach_1;
	if (p_name == "room_beach_0") return TextureRects::room_beach_0;
	if (p_name == "room_house_aon_hallway") return TextureRects::room_house_aon_hallway;
	if (p_name == "room_house_aon_downstairs") return TextureRects::room_house_aon_downstairs;
	if (p_name == "object_house_aon_0") return TextureRects::object_house_aon_0;
	if (p_name == "room_house_aon_kitchen") return TextureRects::room_house_aon_kitchen;
	if (p_name == "object_palmTree") return TextureRects::object_palmTree;
	if (p_name == "character_fauster_fight_idle_0") return TextureRects::character_fauster_fight_idle_0;
	if (p_name == "object_llamaBay_store") return TextureRects::object_llamaBay_store;
	if (p_name == "character_flirtingDoggoLogo") return TextureRects::character_flirtingDoggoLogo;
	if (p_name == "character_martoonitgamer_fight_idle_0") return TextureRects::character_martoonitgamer_fight_idle_0;
	if (p_name == "room_house_aon_guestroom") return TextureRects::room_house_aon_guestroom;
	if (p_name == "character_blackatackle_fight_idle_0") return TextureRects::character_blackatackle_fight_idle_0;
	if (p_name == "character_blueman_overworld_down_talking") return TextureRects::character_blueman_overworld_down_talking;
	if (p_name == "character_blueman_overworld_down") return TextureRects::character_blueman_overworld_down;
	if (p_name == "object_house_aon_livingroom_wall") return TextureRects::object_house_aon_livingroom_wall;
	if (p_name == "object_house_shop_keeper") return TextureRects::object_house_shop_keeper;
	if (p_name == "character_weirdSquidDog_fight_idle_0") return TextureRects::character_weirdSquidDog_fight_idle_0;
	if (p_name == "room_intro_2") return TextureRects::room_intro_2;
	if (p_name == "room_intro_4") return TextureRects::room_intro_4;
	if (p_name == "room_intro_1") return TextureRects::room_intro_1;
	if (p_name == "room_intro_0") return TextureRects::room_intro_0;
	if (p_name == "room_intro_3") return TextureRects::room_intro_3;
	if (p_name == "character_pinkRabbit_fight_idle_0") return TextureRects::character_pinkRabbit_fight_idle_0;
	if (p_name == "object_shopinthewoods") return TextureRects::object_shopinthewoods;
	if (p_name == "object_house_aon_1") return TextureRects::object_house_aon_1;
	if (p_name == "object_house_lab") return TextureRects::object_house_lab;
	if (p_name == "object_house_aon_hallway_wall") return TextureRects::object_house_aon_hallway_wall;
	if (p_name == "character_neamly_overworld_spooky_down") return TextureRects::character_neamly_overworld_spooky_down;
	if (p_name == "character_neamly_overworld_down") return TextureRects::character_neamly_overworld_down;
	if (p_name == "character_lissey_fight_idle_0") return TextureRects::character_lissey_fight_idle_0;
	if (p_name == "character_hauntedRobot_overworld_down_evil") return TextureRects::character_hauntedRobot_overworld_down_evil;
	if (p_name == "character_reiny_fight_idle_0") return TextureRects::character_reiny_fight_idle_0;
	if (p_name == "character_blueman_closeup_neutral") return TextureRects::character_blueman_closeup_neutral;
	if (p_name == "object_house_0") return TextureRects::object_house_0;
	if (p_name == "object_llamaBay_rocks") return TextureRects::object_llamaBay_rocks;
	if (p_name == "character_llamateen_fight_idle_itch_0") return TextureRects::character_llamateen_fight_idle_itch_0;
	if (p_name == "character_llamateen_fight_idle_itch_1") return TextureRects::character_llamateen_fight_idle_itch_1;
	if (p_name == "character_llamateen_fight_idle_1") return TextureRects::character_llamateen_fight_idle_1;
	if (p_name == "character_llamateen_fight_idle_0") return TextureRects::character_llamateen_fight_idle_0;
	if (p_name == "character_caroline_fight_idle_0") return TextureRects::character_caroline_fight_idle_0;
	if (p_name == "UI_floatingMenu") return TextureRects::UI_floatingMenu;
	if (p_name == "character_weirdo_overworld_left_walking_0") return TextureRects::character_weirdo_overworld_left_walking_0;
	if (p_name == "character_weirdo_overworld_left_walking_1") return TextureRects::character_weirdo_overworld_left_walking_1;
	if (p_name == "character_art_fight_dead") return TextureRects::character_art_fight_dead;
	if (p_name == "character_art_fight_idle_0") return TextureRects::character_art_fight_idle_0;
	if (p_name == "character_art_fight_idle_1") return TextureRects::character_art_fight_idle_1;
	if (p_name == "character_art_fight_hurt") return TextureRects::character_art_fight_hurt;
	if (p_name == "character_weirdo_overworld_left_talking") return TextureRects::character_weirdo_overworld_left_talking;
	if (p_name == "character_weirdo_overworld_left") return TextureRects::character_weirdo_overworld_left;
	if (p_name == "character_dogplane_fight_idle_0") return TextureRects::character_dogplane_fight_idle_0;
	if (p_name == "object_battleEffect_hit_1") return TextureRects::object_battleEffect_hit_1;
	if (p_name == "object_battleEffect_hit_3") return TextureRects::object_battleEffect_hit_3;
	if (p_name == "object_battleEffect_hit_2") return TextureRects::object_battleEffect_hit_2;
	if (p_name == "object_battleEffect_hit_0") return TextureRects::object_battleEffect_hit_0;
	if (p_name == "object_house_diner") return TextureRects::object_house_diner;
	if (p_name == "character_snorrplurp_fight_idle_2") return TextureRects::character_snorrplurp_fight_idle_2;
	if (p_name == "character_snorplorp_fight_idle_0") return TextureRects::character_snorplorp_fight_idle_0;
	if (p_name == "character_snorrplurp_fight_idle_1") return TextureRects::character_snorrplurp_fight_idle_1;
	if (p_name == "character_ducko_fight_idle_0") return TextureRects::character_ducko_fight_idle_0;
	if (p_name == "character_ducko_fight_howDareYou_0") return TextureRects::character_ducko_fight_howDareYou_0;
	if (p_name == "character_ducko_fight_howDareYou_1") return TextureRects::character_ducko_fight_howDareYou_1;
	if (p_name == "character_ducko_fight_howDareYou_2") return TextureRects::character_ducko_fight_howDareYou_2;
	if (p_name == "object_house_aon_guestroom_bed") return TextureRects::object_house_aon_guestroom_bed;
	if (p_name == "character_nuayde_fight_idle_body") return TextureRects::character_nuayde_fight_idle_body;
	if (p_name == "character_bunny_overworld_down") return TextureRects::character_bunny_overworld_down;
	if (p_name == "object_house_random_0") return TextureRects::object_house_random_0;
	if (p_name == "room_gameOver") return TextureRects::room_gameOver;
	if (p_name == "character_personAndCamel_overworld_left") return TextureRects::character_personAndCamel_overworld_left;
	if (p_name == "character_personAndCamel_overworld_left_2") return TextureRects::character_personAndCamel_overworld_left_2;
	if (p_name == "character_camel_overworld_idle_0") return TextureRects::character_camel_overworld_idle_0;
	if (p_name == "character_personAndCamel_overworld_down_1") return TextureRects::character_personAndCamel_overworld_down_1;
	if (p_name == "character_camel_overworld_idle_1") return TextureRects::character_camel_overworld_idle_1;
	if (p_name == "object_house_aon_livingroom_granpaClock_1") return TextureRects::object_house_aon_livingroom_granpaClock_1;
	if (p_name == "object_house_aon_livingroom_granpaClock_0") return TextureRects::object_house_aon_livingroom_granpaClock_0;
	if (p_name == "object_house_aon_livingroom_granpaClock_2") return TextureRects::object_house_aon_livingroom_granpaClock_2;
	if (p_name == "character_limespider_fight_idle_booty") return TextureRects::character_limespider_fight_idle_booty;
	if (p_name == "character_llamaBaby_fight_hit") return TextureRects::character_llamaBaby_fight_hit;
	if (p_name == "character_llamaBaby_fight_idle_0") return TextureRects::character_llamaBaby_fight_idle_0;
	if (p_name == "character_llamaBaby_fight_idle_1") return TextureRects::character_llamaBaby_fight_idle_1;
	if (p_name == "UI_textbox") return TextureRects::UI_textbox;
	if (p_name == "character_dadAvocado_overworld_down_talking_0") return TextureRects::character_dadAvocado_overworld_down_talking_0;
	if (p_name == "character_dadAvocado_overworld_down_talking_1") return TextureRects::character_dadAvocado_overworld_down_talking_1;
	if (p_name == "character_avocadomayor_overworld_down") return TextureRects::character_avocadomayor_overworld_down;
	if (p_name == "character_sundeh_overworld_right") return TextureRects::character_sundeh_overworld_right;
	if (p_name == "character_sundeh_overworld_left") return TextureRects::character_sundeh_overworld_left;
	if (p_name == "character_creepyGhost_closeup_glitch_1") return TextureRects::character_creepyGhost_closeup_glitch_1;
	if (p_name == "character_creepyGhost_closeup_glitch_0") return TextureRects::character_creepyGhost_closeup_glitch_0;
	if (p_name == "character_creepyGhost_closeup_glitch_2") return TextureRects::character_creepyGhost_closeup_glitch_2;
	if (p_name == "character_creepyGhost_closeup_neutral") return TextureRects::character_creepyGhost_closeup_neutral;
	if (p_name == "character_creepyGhost_closeup_red") return TextureRects::character_creepyGhost_closeup_red;
	if (p_name == "character_sundeh_overworld_down") return TextureRects::character_sundeh_overworld_down;
	if (p_name == "character_sundeh_overworld_up") return TextureRects::character_sundeh_overworld_up;
	if (p_name == "character_oldAvocadoAndDog_overworld_left_1") return TextureRects::character_oldAvocadoAndDog_overworld_left_1;
	if (p_name == "character_confusnake_fight_idle_0") return TextureRects::character_confusnake_fight_idle_0;
	if (p_name == "character_handman_overworld_down_1") return TextureRects::character_handman_overworld_down_1;
	if (p_name == "character_handman_overworld_down") return TextureRects::character_handman_overworld_down;
	if (p_name == "character_aon_overworld_newspaper_1") return TextureRects::character_aon_overworld_newspaper_1;
	if (p_name == "character_aon_overworld_newspaper_1_talking") return TextureRects::character_aon_overworld_newspaper_1_talking;
	if (p_name == "object_house_aon_tv") return TextureRects::object_house_aon_tv;
	if (p_name == "character_oldAvocadoAndDog_overworld_left") return TextureRects::character_oldAvocadoAndDog_overworld_left;
	if (p_name == "character_oldAvocadoAndDog_overworld_left_2") return TextureRects::character_oldAvocadoAndDog_overworld_left_2;
	if (p_name == "character_buggy_fight_idle_0") return TextureRects::character_buggy_fight_idle_0;
	if (p_name == "character_buggy_fight_idle_1") return TextureRects::character_buggy_fight_idle_1;
	if (p_name == "character_aon_closeup_heh") return TextureRects::character_aon_closeup_heh;
	if (p_name == "character_aon_closeup_happy_talking") return TextureRects::character_aon_closeup_happy_talking;
	if (p_name == "character_aon_closeup_happy") return TextureRects::character_aon_closeup_happy;
	if (p_name == "character_aon_closeup_suprised") return TextureRects::character_aon_closeup_suprised;
	if (p_name == "character_aon_closeup_sad_talking") return TextureRects::character_aon_closeup_sad_talking;
	if (p_name == "character_aon_closeup_suprised_talking") return TextureRects::character_aon_closeup_suprised_talking;
	if (p_name == "character_aon_closeup_sweat") return TextureRects::character_aon_closeup_sweat;
	if (p_name == "character_aon_closeup_sweat_talking") return TextureRects::character_aon_closeup_sweat_talking;
	if (p_name == "character_aon_closeup_angry") return TextureRects::character_aon_closeup_angry;
	if (p_name == "character_aon_closeup_angry_talking") return TextureRects::character_aon_closeup_angry_talking;
	if (p_name == "character_aon_closeup_sad") return TextureRects::character_aon_closeup_sad;
	if (p_name == "character_aon_closeup_huh_talking") return TextureRects::character_aon_closeup_huh_talking;
	if (p_name == "character_aon_closeup_huh") return TextureRects::character_aon_closeup_huh;
	if (p_name == "character_aon_closeup_heh_talking") return TextureRects::character_aon_closeup_heh_talking;
	if (p_name == "character_aon_overworld_down_walking_1") return TextureRects::character_aon_overworld_down_walking_1;
	if (p_name == "character_aon_overworld_up_walking_1") return TextureRects::character_aon_overworld_up_walking_1;
	if (p_name == "character_aon_overworld_up_walking_0") return TextureRects::character_aon_overworld_up_walking_0;
	if (p_name == "character_aon_overworld_down") return TextureRects::character_aon_overworld_down;
	if (p_name == "character_aon_overworld_down_talking") return TextureRects::character_aon_overworld_down_talking;
	if (p_name == "character_aon_overworld_down_walking_0") return TextureRects::character_aon_overworld_down_walking_0;
	if (p_name == "character_aon_overworld_up") return TextureRects::character_aon_overworld_up;
	if (p_name == "character_aon_overworld_right_walking_0") return TextureRects::character_aon_overworld_right_walking_0;
	if (p_name == "character_aon_overworld_right_walking_1") return TextureRects::character_aon_overworld_right_walking_1;
	if (p_name == "character_aon_overworld_left_walking_1") return TextureRects::character_aon_overworld_left_walking_1;
	if (p_name == "character_aon_overworld_left") return TextureRects::character_aon_overworld_left;
	if (p_name == "character_aon_overworld_left_walking_0") return TextureRects::character_aon_overworld_left_walking_0;
	if (p_name == "character_aon_overworld_left_walking_0_worried") return TextureRects::character_aon_overworld_left_walking_0_worried;
	if (p_name == "character_aon_overworld_left_walking_1_worried") return TextureRects::character_aon_overworld_left_walking_1_worried;
	if (p_name == "character_aon_overworld_left_worried") return TextureRects::character_aon_overworld_left_worried;
	if (p_name == "character_aon_overworld_onLegs_left_0") return TextureRects::character_aon_overworld_onLegs_left_0;
	if (p_name == "character_aon_overworld_right") return TextureRects::character_aon_overworld_right;
	if (p_name == "character_flynn_tired") return TextureRects::character_flynn_tired;
	if (p_name == "object_house_diner_door_2") return TextureRects::object_house_diner_door_2;
	if (p_name == "object_house_diner_door_1") return TextureRects::object_house_diner_door_1;
	if (p_name == "object_house_diner_door_3") return TextureRects::object_house_diner_door_3;
	if (p_name == "object_house_diner_door_0") return TextureRects::object_house_diner_door_0;
	if (p_name == "character_nuayde_fight_idle_arm_left_0") return TextureRects::character_nuayde_fight_idle_arm_left_0;
	if (p_name == "character_nuayde_fight_idle_arm_left_1") return TextureRects::character_nuayde_fight_idle_arm_left_1;
	if (p_name == "character_nuayde_fight_idle_arm_right_0") return TextureRects::character_nuayde_fight_idle_arm_right_0;
	if (p_name == "character_nuayde_fight_idle_arm_right_1") return TextureRects::character_nuayde_fight_idle_arm_right_1;
	if (p_name == "character_avocadoGuy_overworld_down") return TextureRects::character_avocadoGuy_overworld_down;
	if (p_name == "character_avocadoGuy_overworld_down_talking") return TextureRects::character_avocadoGuy_overworld_down_talking;
	if (p_name == "character_aon_overworld_onLegs_left_talking") return TextureRects::character_aon_overworld_onLegs_left_talking;
	if (p_name == "character_aon_overworld_onLegs_left") return TextureRects::character_aon_overworld_onLegs_left;
	if (p_name == "character_aon_overworld_onLegs_left_1") return TextureRects::character_aon_overworld_onLegs_left_1;
	if (p_name == "object_house_aon_guestroom_bed_overlay") return TextureRects::object_house_aon_guestroom_bed_overlay;
	if (p_name == "character_aon_overworld_newspaper_0") return TextureRects::character_aon_overworld_newspaper_0;
	if (p_name == "character_flynn_overworld_snoring_0") return TextureRects::character_flynn_overworld_snoring_0;
	if (p_name == "character_flynn_overworld_up_walking_1") return TextureRects::character_flynn_overworld_up_walking_1;
	if (p_name == "character_flynn_overworld_up_walking_0") return TextureRects::character_flynn_overworld_up_walking_0;
	if (p_name == "character_flynn_overworld_snoring_1") return TextureRects::character_flynn_overworld_snoring_1;
	if (p_name == "character_flynn_overworld_right") return TextureRects::character_flynn_overworld_right;
	if (p_name == "character_flynn_overworld_left_walking_1") return TextureRects::character_flynn_overworld_left_walking_1;
	if (p_name == "character_flynn_overworld_left_walking_0") return TextureRects::character_flynn_overworld_left_walking_0;
	if (p_name == "character_flynn_overworld_left_sitting") return TextureRects::character_flynn_overworld_left_sitting;
	if (p_name == "character_flynn_overworld_left") return TextureRects::character_flynn_overworld_left;
	if (p_name == "character_flynn_overworld_down_walking_1") return TextureRects::character_flynn_overworld_down_walking_1;
	if (p_name == "character_flynn_overworld_down_walking_0") return TextureRects::character_flynn_overworld_down_walking_0;
	if (p_name == "character_flynn_overworld_down") return TextureRects::character_flynn_overworld_down;
	if (p_name == "character_flynn_overworld_up") return TextureRects::character_flynn_overworld_up;
	if (p_name == "UI_title") return TextureRects::UI_title;
	if (p_name == "character_flynn_overworld_right_walking_0") return TextureRects::character_flynn_overworld_right_walking_0;
	if (p_name == "character_flynn_overworld_right_walking_1") return TextureRects::character_flynn_overworld_right_walking_1;
	if (p_name == "character_nuayde_fight_idle_face_hurt") return TextureRects::character_nuayde_fight_idle_face_hurt;
	if (p_name == "character_nuayde_fight_idle_face") return TextureRects::character_nuayde_fight_idle_face;
	if (p_name == "character_nuayde_fight_idle_face_rip") return TextureRects::character_nuayde_fight_idle_face_rip;
	if (p_name == "character_pinkshirtedllama_overworld_down_walking_0") return TextureRects::character_pinkshirtedllama_overworld_down_walking_0;
	if (p_name == "character_pinkshirtedllama_overworld_down_walking_1") return TextureRects::character_pinkshirtedllama_overworld_down_walking_1;
	if (p_name == "character_pinkshirtedllama_overworld_down") return TextureRects::character_pinkshirtedllama_overworld_down;
	if (p_name == "character_pinkshirtedllama_overworld_down_talking") return TextureRects::character_pinkshirtedllama_overworld_down_talking;
	if (p_name == "object_house_aon_livingroom_table") return TextureRects::object_house_aon_livingroom_table;
	if (p_name == "object_pomHeadStatue") return TextureRects::object_pomHeadStatue;
	if (p_name == "character_pinkRabbit_overworld_down_talking") return TextureRects::character_pinkRabbit_overworld_down_talking;
	if (p_name == "character_pinkRabbit_overworld_down") return TextureRects::character_pinkRabbit_overworld_down;
	if (p_name == "character_pinkRabbit_overworld_down_walking_0") return TextureRects::character_pinkRabbit_overworld_down_walking_0;
	if (p_name == "object_house_aon_livingroom_couch") return TextureRects::object_house_aon_livingroom_couch;
	if (p_name == "character_avocadoBoy_overworld_down_talking_1") return TextureRects::character_avocadoBoy_overworld_down_talking_1;
	if (p_name == "object_fire_0") return TextureRects::object_fire_0;
	if (p_name == "object_fire_2") return TextureRects::object_fire_2;
	if (p_name == "object_house_aon_gramophone") return TextureRects::object_house_aon_gramophone;
	if (p_name == "object_fire_1") return TextureRects::object_fire_1;
	if (p_name == "character_margret_lemonadeStand") return TextureRects::character_margret_lemonadeStand;
	if (p_name == "character_magret_lemonadeStand_talking") return TextureRects::character_magret_lemonadeStand_talking;
	if (p_name == "object_pomStatue") return TextureRects::object_pomStatue;
	if (p_name == "character_avocadoBoy_overworld_down_talking_0") return TextureRects::character_avocadoBoy_overworld_down_talking_0;
	if (p_name == "character_avocadoBoy_overworld_down") return TextureRects::character_avocadoBoy_overworld_down;
	if (p_name == "character_tailance_overworld_down") return TextureRects::character_tailance_overworld_down;
	if (p_name == "character_lissey_overworld_down") return TextureRects::character_lissey_overworld_down;
	if (p_name == "character_joggingsnake_overworld_left") return TextureRects::character_joggingsnake_overworld_left;
	if (p_name == "character_joggingsnake_overworld_left_walking_0") return TextureRects::character_joggingsnake_overworld_left_walking_0;
	if (p_name == "character_joggingsnake_overworld_left_walking_1") return TextureRects::character_joggingsnake_overworld_left_walking_1;
	if (p_name == "character_cat_fight_idle_0") return TextureRects::character_cat_fight_idle_0;
	if (p_name == "character_cat_fight_idle_1") return TextureRects::character_cat_fight_idle_1;
	if (p_name == "character_birdhat_overworld_left_talking") return TextureRects::character_birdhat_overworld_left_talking;
	if (p_name == "character_birdhat_overworld_left") return TextureRects::character_birdhat_overworld_left;
	if (p_name == "character_creepyGhost_overworld_down_red_1") return TextureRects::character_creepyGhost_overworld_down_red_1;
	if (p_name == "character_creepyghost_overworld_down_red_0") return TextureRects::character_creepyghost_overworld_down_red_0;
	if (p_name == "character_creepyGhost_overworld_down_appearing_8") return TextureRects::character_creepyGhost_overworld_down_appearing_8;
	if (p_name == "character_creepyGhost_overworld_down_appearing_7") return TextureRects::character_creepyGhost_overworld_down_appearing_7;
	if (p_name == "character_creepyGhost_overworld_down_appearing_6") return TextureRects::character_creepyGhost_overworld_down_appearing_6;
	if (p_name == "character_creepyGhost_overworld_down_red_3") return TextureRects::character_creepyGhost_overworld_down_red_3;
	if (p_name == "character_creepyGhost_overworld_down_appearing_5") return TextureRects::character_creepyGhost_overworld_down_appearing_5;
	if (p_name == "character_creepyGhost_overworld_down_appearing_4") return TextureRects::character_creepyGhost_overworld_down_appearing_4;
	if (p_name == "character_creepyGhost_overworld_down_talking_creepy_0") return TextureRects::character_creepyGhost_overworld_down_talking_creepy_0;
	if (p_name == "character_creepyGhost_overworld_down_appearing_3") return TextureRects::character_creepyGhost_overworld_down_appearing_3;
	if (p_name == "character_creepyGhost_overworld_down_appearing_2") return TextureRects::character_creepyGhost_overworld_down_appearing_2;
	if (p_name == "character_creepyGhost_overworld_down_talking_creepy_1") return TextureRects::character_creepyGhost_overworld_down_talking_creepy_1;
	if (p_name == "character_creepyGhost_overworld_down") return TextureRects::character_creepyGhost_overworld_down;
	if (p_name == "character_creepyGhost_overworld_down_red_2") return TextureRects::character_creepyGhost_overworld_down_red_2;
	if (p_name == "character_creepyGhost_overworld_down_talking") return TextureRects::character_creepyGhost_overworld_down_talking;
	if (p_name == "UI_hearts") return TextureRects::UI_hearts;
	if (p_name == "character_limespider_fight_idle_leg_right_2") return TextureRects::character_limespider_fight_idle_leg_right_2;
	if (p_name == "character_limespider_fight_idle_leg_left_2") return TextureRects::character_limespider_fight_idle_leg_left_2;
	if (p_name == "object_checkpoint_open") return TextureRects::object_checkpoint_open;
	if (p_name == "object_checkpoint_closed") return TextureRects::object_checkpoint_closed;
	if (p_name == "character_depressedAvocado_overworld_right") return TextureRects::character_depressedAvocado_overworld_right;
	if (p_name == "character_depressedAvocado_overworld_right_walking_1") return TextureRects::character_depressedAvocado_overworld_right_walking_1;
	if (p_name == "character_creepyGhost_overworld_down_appearing_1") return TextureRects::character_creepyGhost_overworld_down_appearing_1;
	if (p_name == "character_depressedAvocado_overworld_right_walking_0") return TextureRects::character_depressedAvocado_overworld_right_walking_0;
	if (p_name == "character_limespider_fight_idle_leg_right_1") return TextureRects::character_limespider_fight_idle_leg_right_1;
	if (p_name == "character_limespider_fight_idle_leg_left_1") return TextureRects::character_limespider_fight_idle_leg_left_1;
	if (p_name == "object_whoopeeCushion") return TextureRects::object_whoopeeCushion;
	if (p_name == "character_cat_overworld_down") return TextureRects::character_cat_overworld_down;
	if (p_name == "character_cat_overworld_down_talking_1") return TextureRects::character_cat_overworld_down_talking_1;
	if (p_name == "character_limespider_fight_idle_face_2") return TextureRects::character_limespider_fight_idle_face_2;
	if (p_name == "character_limespider_fight_idle_face_4") return TextureRects::character_limespider_fight_idle_face_4;
	if (p_name == "character_limespider_fight_idle_face_5") return TextureRects::character_limespider_fight_idle_face_5;
	if (p_name == "character_limespider_fight_idle_face_3") return TextureRects::character_limespider_fight_idle_face_3;
	if (p_name == "character_limespider_fight_idle_face_6") return TextureRects::character_limespider_fight_idle_face_6;
	if (p_name == "character_limespider_fight_idle_face_7") return TextureRects::character_limespider_fight_idle_face_7;
	if (p_name == "character_limespider_fight_idle_face_1") return TextureRects::character_limespider_fight_idle_face_1;
	if (p_name == "character_limespider_fight_idle_face_0") return TextureRects::character_limespider_fight_idle_face_0;
	if (p_name == "character_limespider_fight_idle_leg_right_0") return TextureRects::character_limespider_fight_idle_leg_right_0;
	if (p_name == "character_limespider_fight_idle_leg_left_0") return TextureRects::character_limespider_fight_idle_leg_left_0;
	if (p_name == "character_sandperson_0_overworld_down") return TextureRects::character_sandperson_0_overworld_down;
	if (p_name == "character_sandperson_0_overworld_down_talking") return TextureRects::character_sandperson_0_overworld_down_talking;
	if (p_name == "object_lemonadeStand_table") return TextureRects::object_lemonadeStand_table;
	if (p_name == "character_limespider_fight_idle_leg_right_3") return TextureRects::character_limespider_fight_idle_leg_right_3;
	if (p_name == "character_limespider_fight_idle_leg_left_3") return TextureRects::character_limespider_fight_idle_leg_left_3;
	if (p_name == "character_limespider_fight_idle_fangs_0") return TextureRects::character_limespider_fight_idle_fangs_0;
	if (p_name == "character_limespider_fight_idle_fangs_1") return TextureRects::character_limespider_fight_idle_fangs_1;
	if (p_name == "character_buggy_overworld_down") return TextureRects::character_buggy_overworld_down;
	if (p_name == "character_buggy_overworld_downtalk") return TextureRects::character_buggy_overworld_downtalk;
	if (p_name == "character_buggy_overworld_down_walking_0") return TextureRects::character_buggy_overworld_down_walking_0;
	if (p_name == "character_buggy_overworld_up") return TextureRects::character_buggy_overworld_up;
	if (p_name == "character_buggy_overworld_down_walking_1") return TextureRects::character_buggy_overworld_down_walking_1;
	if (p_name == "object_house_aon_avocadoPlant") return TextureRects::object_house_aon_avocadoPlant;
	if (p_name == "object_table") return TextureRects::object_table;
	if (p_name == "object_house_aon_plant") return TextureRects::object_house_aon_plant;
	if (p_name == "character_ducko_overworld_left_walking_0") return TextureRects::character_ducko_overworld_left_walking_0;
	if (p_name == "character_ducko_overworld_left_walking_1") return TextureRects::character_ducko_overworld_left_walking_1;
	if (p_name == "character_ducko_overworld_left") return TextureRects::character_ducko_overworld_left;
	if (p_name == "character_dogplane_overworld_right") return TextureRects::character_dogplane_overworld_right;
	if (p_name == "character_flynn_overworld_lying") return TextureRects::character_flynn_overworld_lying;
	if (p_name == "object_minecart_side_1") return TextureRects::object_minecart_side_1;
	if (p_name == "object_minecart_side_0") return TextureRects::object_minecart_side_0;
	if (p_name == "object_minecart_down_0") return TextureRects::object_minecart_down_0;
	if (p_name == "object_minecart_down_1") return TextureRects::object_minecart_down_1;
	if (p_name == "character_creepyGhost_overworld_down_appearing_0") return TextureRects::character_creepyGhost_overworld_down_appearing_0;
	if (p_name == "character_art_overworld_down_walking_1") return TextureRects::character_art_overworld_down_walking_1;
	if (p_name == "character_cuteDog_overworld_down") return TextureRects::character_cuteDog_overworld_down;
	if (p_name == "UI_button_left") return TextureRects::UI_button_left;
	if (p_name == "character_art_overworld_down") return TextureRects::character_art_overworld_down;
	if (p_name == "character_art_overworld_down_walking_0") return TextureRects::character_art_overworld_down_walking_0;
	if (p_name == "UI_button_left_pressed") return TextureRects::UI_button_left_pressed;
	if (p_name == "object_rail_down") return TextureRects::object_rail_down;
	if (p_name == "object_house_aon_lamp") return TextureRects::object_house_aon_lamp;
	if (p_name == "UI_heart") return TextureRects::UI_heart;
	if (p_name == "object_bone") return TextureRects::object_bone;
	if (p_name == "character_sandperson_1_overworld_down") return TextureRects::character_sandperson_1_overworld_down;
	if (p_name == "UI_button_johnCena_pressed") return TextureRects::UI_button_johnCena_pressed;
	if (p_name == "UI_button_johnCena") return TextureRects::UI_button_johnCena;
	if (p_name == "object_dogFood") return TextureRects::object_dogFood;
	if (p_name == "object_cat") return TextureRects::object_cat;
	if (p_name == "object_rail_right") return TextureRects::object_rail_right;
	return sf::IntRect();
};